<?php

use App\Domain\User\Enums\RoleEnum; 

return [
    RoleEnum::OWNER->value => [
        'tenant:view',
        'tenant:edit',
        'tenant:delete',
        'tenant:invite_user',
        'tenant:remove_user',
        'project:view',
        'project:view_all',
        'project:create',
        'project:edit',
        'project:delete',
        'task:view',
        'task:view_all',
        'task:view_own',
        'task:create',
        'task:edit',
        'task:edit_own',
        'task:edit_all',
        'task:delete',
        'task:delete_own',
        'task:delete_all',
        'task:assign',
        'task:edit_status',
        'team:view',
        'team:manage',
        'dashboard:view',
    ],
    RoleEnum::ADMIN->value => [
        'tenant:view',
        'project:view',
        'project:view_all',
        'project:create',
        'project:edit',
        'project:delete',
        'task:view',
        'task:view_all',
        'task:view_own',
        'task:create',
        'task:edit',
        'task:edit_own',
        'task:edit_all',
        'task:delete',
        'task:delete_all',
        'task:assign',
        'task:edit_status',
        'team:view',
        'team:manage',
        'dashboard:view',
    ],
    RoleEnum::MEMBER->value => [
        'tenant:view',
        'project:view',
        'project:view_all',
        'task:view',
        'task:view_own',
        'task:create',
        'task:edit_own',
        'task:edit_status',
        'team:view',
        'dashboard:view',
    ],
];
 